image:
- Visual Studio 2019
- macOS
- Ubuntu

skip_branch_with_pr: true
stack: python 3.10

environment:
  GITHUB_TOKEN:
    secure: N5aGlRzv9QFj5KCToqpa7jbJH0s5iJazkcve+jUqXgZtE2o1M1MFfn93l0mHyLH4

install:
- pip install -r requirements.txt

build_script:
- pyinstaller main.py --name Flet-Utils --noconsole --noconfirm --onefile --icon "pc-logo.png"
test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

#
#   Windows package
#
for:
-
  matrix:
    only:
    - image: Visual Studio 2019

  after_build:
  - 7z a Flet-Utils-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: Flet-Utils-windows.zip

#
#   macOS package
#
-
  matrix:
    only:
    - image: macOS

  after_build:
  - tar -czvf Flet-Utils-macos.tar.gz -C dist Flet-Utils.app

  artifacts:
  - path: Flet-Utils-macos.tar.gz

#
#   Linux package
#
-
  matrix:
    only:
    - image: Ubuntu

  after_build:
  - tar -czvf Flet-Utils-linux.tar.gz -C dist Flet-Utils

  artifacts:
  - path: Flet-Utils-linux.tar.gz
